### ISSUE TITLE
Why there is a dependency to @prezly/slate-types?

### ISSUE THREAD

**Issue by e1himself** [prezly/theme-kit-nextjs#29]
I've noticed that this package does depend on `@prezly/slate-types`:

https://github.com/prezly/theme-kit-nextjs/blob/06fd4e83c83bc73b5ee281876035af899a109c09/package.json#L52

But I couldn't find any actual usage in the code. Is it really needed @oleg-semyonov @kudlajz?

**Comment by oleg-semyonov** [comment]
No, it's not used, good catch!
